// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hospital.DataAcessLayer.ORM;

#nullable disable

namespace hospital.DataAcessLayer.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20211216164812_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("hospital.Domain.Entities.Mural", b =>
                {
                    b.Property<long>("Mural_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Mural_Id"), 1L, 1);

                    b.Property<string>("Mural_Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mural_Aviso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Mural_Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mural_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mural_Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mural_Id");

                    b.ToTable("Mural");
                });
#pragma warning restore 612, 618
        }
    }
}
